{% set name = "gwsumm" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd1c67602a5e8e918cc39a3d3eebf89986d8c7e1b3900b40b321500f23670ad7

build:
  number: 0
  skip: true  # [win]
  skip: true  # [osx]
  skip: true  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python >=3.5
    - python-dateutil
    - lxml
    - numpy >=1.10
    - scipy >=1.2.0
    - matplotlib >=2.0
    - astropy >=1.2.1
    - lalsuite
    - gwtrigfind
    - gwdatafind
    - lscsoft-glue >=1.60.0
    - ligo-segments
    - pygments
    - MarkupPy
    - markdown
    - gwdetchar >=1.0.0
    - gwpy >=1.0.0
    - configparser  # [py<36]

test:
  requires:
    - pytest >=2.8,<3.7
    - coverage
    - flake8
  imports:
    - gwsumm
    - gwsumm.archive
    - gwsumm.channels
    - gwsumm.config
    - gwsumm.data
    - gwsumm.data.coherence
    - gwsumm.data.mathutils
    - gwsumm.data.range
    - gwsumm.data.spectral
    - gwsumm.data.timeseries
    - gwsumm.data.utils
    - gwsumm.globalv
    - gwsumm.html
    - gwsumm.html.bootstrap
    - gwsumm.html.html5
    - gwsumm.html.static
    - gwsumm.io
    - gwsumm.mode
    - gwsumm.segments
    - gwsumm.state
    - gwsumm.state.all
    - gwsumm.state.registry
    - gwsumm.triggers
    - gwsumm.units
    - gwsumm.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check scripts run ok
    - gw_summary --help
    - gw_summary day --help
    - gw_summary week --help
    - gw_summary month --help
    - gw_summary gps --help
    - gw_summary_pipe --help
    - gwsumm-plot-guardian --help
    - gwsumm-plot-triggers --help

about:
  home: https://github.com/gwpy/gwsumm
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A python toolbox for Advanced LIGO detector characterisation
  description: |
    This package provides a python toolbox widely used for Advanced
    LIGO detector characterisation and data quality. The tools contained
    within summarise and archive sundry facets of the performance of the
    LIGO instruments, and archive these data in a nested HTML structure.

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
