travis:
  secure:
    BINSTAR_TOKEN: bIu5YuQb8I1lMgnR9iUdh5tHBm/Ag7+fpew43d1K3oiZ/mVqIP7fUZbszqNdtyCHcdIZ9iZp6QFIzEdP4U7qqbDlQMGBMjeOBmHB66LEqASwMK621wCjTNb9sJCt9z0gOiZAywnzsBXgFX+v6dF3ONsqVJaC6LQkMZKwOnK5WLMy9BbSi2fjGNd2hzYLzNkV2rI0jV1XGKmJ0s6DW0+vYanOxzueXvLv83THjIhohLpKyhGS00ab/Dtszm4jf2fMOUeovd0w4fqOn/Nso9J7CuOj/Rjrs3ojUOYU7aFm+v573fXTWjrrgMllMi2rEahEKyfQrgw1jOPlBeGQAQNzxSKTxgZsHytrBPYrzP3xmr6msSn5pFYCKd/b5fZHpyo692yYRLgRy2Nr0yHJ9E2PCfxPm16YF9orVUW5d/0ITMGOAtvCRaKbTHUroWcYbFNkNbjMq1FaqWooqNCZNwxXuBQhobnHvk2l9a1gxo7J7GwE8pRBNiIzTJFifVelffuRTqL5SCz8Dd6HXsWqWnWg5HbKlkRH6TXPRRBdzRHZLZ9DZbYEhndqpkFHiqrEnwq3CL8s+D+dGzXwoLk52Lvyu/r156G6NyoS2k9wJG0PK/owxnx9K74OJwoVQmI056g2Z7RjRgLTeL6L3gqFVrP2ssF4s8q3/s6+acN7t5E6Vfw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
